### ISSUE TITLE
Aspect use in enumeration types

### ISSUE THREAD

**Issue by jklmnn** [Componolit/RecordFlux-language#14]
I have noticed that the `Size` aspect can be accessed directly via `F_Size` in range and modular types but is only an aspect in the aspect list for enumeration types. Since enumerations can only have two aspects, `Size` and `Always_Valid` I'd propose to remove aspects from enumeration types and add these properties similar to the properties for range and modular types:
```Python
class EnumerationTypeDef(TypeDef):

    elements = Field(type=EnumerationDef)
    size = Field(type=Aspect)
	always_valid = Field(type=Aspect)
```
@senier @treiher what are your thoughts on that?

**Comment by senier** [comment]
The difference is that modulars only support a single aspect (`Size`). Hence I decided to simplify the parser here. If we ever add more aspects to modulars, it will become as complicated as enums.
