### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by treiher** [Componolit/RecordFlux-language#6]
The RecordFlux language should versioned.

#### O1: Semantic Versioning

- `MAJOR.MINOR.PATCH` (e.g., `0.1.0`)

#### O2: Date-based Versioning

- O2.1: `YEAR.MONTH.PATCH` (e.g., `2021.1.0`)
- O2.2: `SHORTYEAR.MONTH.PATCH` (e.g., `21.1.0`)
- O2.3: `YEAR.PATCH` (e.g., `2021.0`)
- O2.4: `SHORTYEAR.PATCH` (e.g., `21.0`)

**Comment by senier** [comment]
I clearly prefer `O1` for the language, as it allows to tell apart incompatible versions. We would increment `MAJOR` for breaking changes (old spec cannot be handled by new parser), `MINOR` for loss of forward compatibility (new specs cannot be parsed by old parser) and `PATCH` for fixes in the parser that do not affect the language.

**Comment by senier** [comment]
Added a tag [`v0.1.0`](https://github.com/Componolit/RecordFlux-language/releases/tag/v0.1.0). While a version number API is [now available on langkit master](https://github.com/AdaCore/langkit/commit/7c352c396aabfbe652ddebeccc47fb0f2aec9fcc), I don't want to switch from the release to `master` just now. I'll keep this ticket open to add an actual version number to the parser once we use a `langkit` version that supports it.
